// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avjdagipcmkvplwlonwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2amRhZ2lwY21rdnBsd2xvbndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTc4OTMsImV4cCI6MjA2OTkzMzg5M30.ErksT792yTniSaMV3Dpgx1vgZkOpFyFbMsM8fKMVyyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});